### ISSUE TITLE
CRN dataset scale error

### ISSUE THREAD

**Issue by yjcaimeow** [junzhezhang/shape-inversion#1]
Hi, @junzhezhang 

Do you notice the scale problem of CRN paper's data? The scales are not match for partial and complete.

And how do you deal with the problem, since your main dataset is from CRN.

Here is the issue you can reference.
https://github.com/xiaogangw/cascaded-point-completion/issues/11

Best,
Yingjie CAI

**Comment by junzhezhang** [comment]
Hi @yjcaimeow ,

Thanks for pointing this out. We noticed it recently. 

Due to the scale error, I think ShapeInversion's performance was underestimated, whereas most of the existing methods should not be affected, due to their training and testing differences.

Please feel free to switch to other existing datasets derived from ShapeNet. 

Thanks,
Junzhe
